export const projectList = [
  {
    title: 'Gamepoint Performance',
    href: 'https://www.gamepointperformance.com/',
    background: 'bg-slate-900',
    imagePath: '/src/assets/gpp.png',
    altText: 'Gamepoint Performance logo.',
    body: `Website redesign and signup feature implementation for Gamepoint Performance's online business and training offerings.`,
    techStack: ['Resend', 'Supabase', 'React hook form'],
  },
  {
    title: 'Minnesota Winter League',
    href: 'https://www.mplswinterleague.com/',
    background: 'bg-blue-400',
    imagePath: '/src/assets/winter-league.png',
    altText: 'Cloudy white sphere resembling a snowball.',
    body: 'Feature rich webapp for a local ultimate frisbee community league. Signup, register, or create a team with friends!',
    techStack: ['Firebase', 'TypeScript', 'Stripe'],
  },
  {
    title: 'Tournament Rating System',
    href: 'https://tundra-santa.vercel.app/',
    background: 'bg-emerald-400',
    imagePath: '/src/assets/tournament-rating.png',
    altText: 'Three filled circles in increasing size.',
    body: 'Applied statistical analysis to large multiplayer data set for online board game tournaments.',
    techStack: ['Nextjs', 'Python', 'Supabase'],
  },
  {
    title: 'Engage Plus',
    href: 'https://engageplus.vercel.app/',
    background: 'bg-red-500',
    imagePath: '/src/assets/engage.png',
    altText: 'Video game character in a fighting stance',
    body: 'Data visualization project with large data sets, high interactivity, and feature rich UI.',
    techStack: ['TypeScript', 'Custom Hooks', 'Tailwind CSS'],
  },
  {
    title: 'Matchup Project',
    href: 'https://balanced-workforce.vercel.app/',
    background: 'bg-orange-400',
    imagePath: '/src/assets/matchup.png',
    altText: 'Blue diamond',
    body: 'A public voting experiment to determine the balance of various match-ups in the board game "Scythe".',
    techStack: ['React', 'Supabase', 'Edge functions'],
  },
  {
    title: 'Rival Dex',
    href: 'https://rival-dex.vercel.app/',
    background: 'bg-violet-500',
    imagePath: '/src/assets/rival-dex.png',
    altText: 'Gary Oak standing confidently with hand solute',
    body: 'Pokémon API inspired webapp complete with data visualization, multi-method authentication, and several UI themes.',
    techStack: ['Firebase', 'Authentication', 'Local storage'],
  },
  {
    title: 'Hero Wind',
    href: 'https://hero-wind.vercel.app/',
    background: 'bg-yellow-400',
    imagePath: '/src/assets/hero-wind.png',
    altText: 'Wonder Woman arms crossed, smiling',
    body: 'LLM data set analyzed with recharts and filtered searching capability with the added bonus of a superhero theme.',
    techStack: ['Superhero API', 'Radix', 'Stitches'],
  },
]
